### ISSUE TITLE
UnboundLocalError: cannot access local variable 'amino' where it is not associated with a value

### ISSUE THREAD

**Issue by Habubinator** [dee-shar/amino_coin_generator#33]
```cmd
+---+----------------+----------------------+
| 1 | Generate Coins | AminoCoinGeneratorBo |
| 2 | Transfer Coins |                      |
+---+----------------+----------------------+
[Select]::: 2
Traceback (most recent call last):
  File "C:\...\AminoCoinGeneratorBo-main\main.py", line 46, in <module>
    utils.start_generator()
  File "C:\...\AminoCoinGeneratorBo-main\src\utils.py", line 114, in start_generator
    ndc_id = amino.Amino().get_from_code(
             ^^^^^
UnboundLocalError: cannot access local variable 'amino' where it is not associated with a value
```

Same thing is for the first command

**Comment by dee-shar** [comment]
fixed
